### ISSUE TITLE
Fatal error: Class 'View_Error_500' not found

### ISSUE THREAD

**Issue by lenton** [kohana/kohanaframework.org#22]
When accessing the website (http://kohanaframework.org) I randomly get the following fatal error when refreshing:

```
Fatal error: Class 'View_Error_500' not found in /var/www/application/classes/kohana/exception.php on line 27
```

**Comment by shadowhand** [comment]
I see it too, very strange. I'll try redeploying.

**Comment by shadowhand** [comment]
Rebuild seems to have fixed it. Let me know if you continue to see issues.
