### ISSUE TITLE
kohanaframework.org is not accessible

### ISSUE THREAD

**Issue by raku** [kohana/kohanaframework.org#26]
When I try to access kohana website I get this message:

This site is on an older infrastructure that will be decomissioned in the near future.
If you are the site administrator, simply log into your admin panel and migrate to the new V2 infrastrucure.
Please contact us if you have any questions, or read the following guide to learn more.

Can you check please?

**Comment by enov** [comment]
Thanks for reporting @raku!

@shadowhand could you kindly have a look at this?

**Comment by enov** [comment]
@shadowhand, pinging you again, in case you still did not notice, thanks.

**Comment by shadowhand** [comment]
@enov yes I've seen it. Servers have been migrated, but still waiting for things to come online.

**Comment by enov** [comment]
Thank you for taking care of this.

**Comment by shadowhand** [comment]
Website is back up now. Old forums are taking a little bit longer, migration didn't transfer completely.

**Comment by shadowhand** [comment]
Old forums are back up too. Hooray!

**Comment by enov** [comment]
Thanks @shadowhand

**Comment by raku** [comment]
:+1:
