### ISSUE TITLE
Kohana documentation media files broken

### ISSUE THREAD

**Issue by shadowhand** [kohana/kohanaframework.org#27]
https://kohanaframework.org/3.3/guide-media/css/print.css displays:

```
ErrorException [ Fatal Error ]: Call to undefined function http_get_request_headers()
SYSPATH/classes/Kohana/HTTP.php [ 163 ]
```

**Comment by enov** [comment]
Looks good to me. Did you fix this already?

**Comment by enov** [comment]
@shadowhand, there is a [similar post](http://discourse.kohanaframework.org/t/what-has-happened-kohanaframework-org-user-guide/658/4) in the forums for the [v3.1 guide](http://kohanaframework.org/3.1/guide/):

Gives me the same `ErrorException`:

![image](https://cloud.githubusercontent.com/assets/4045110/7119027/c5ebf71e-e20b-11e4-9262-00ab71f06610.png)

**Comment by raku** [comment]
Also http://kohanaframework.org/3.3/guide-media/css/screen.css don't get loaded

**Comment by enov** [comment]
Looks fixed again. Could you confirm @raku?

**Comment by raku** [comment]
No, it isn't :(
![kohana-error](https://cloud.githubusercontent.com/assets/158101/7256281/d9466af0-e856-11e4-9455-01a453c42996.jpg)

**Comment by randomecho** [comment]
The print.css file now brings up this: 


![kohana-css-2150424](https://cloud.githubusercontent.com/assets/743877/7331152/dd01526c-ead2-11e4-8392-1e0998508365.png)

**Comment by enov** [comment]
@shadowhand this is to report that, while v3.1 guide is still unaccessible, both links (screen.css and print.css) are *sometimes* working from my side, currently I can access the v.3.3 docs without problems.

Now, regarding `http_get_request_headers` ErrorException, it seems to me that we have a newer (>=2.0.0) [HTTP PECL](https://pecl.php.net/package/pecl_http) installed.

So, we should probably add support for the newer extension. On [that line](https://github.com/kohana/core/blob/3.3/master/classes/Kohana/HTTP.php#L163) we can compare the extension's version and do something like this:

```php
$headers = version_compare(phpversion('http'), '2.0.0', '>=') ?
	\http\Env::getRequestHeader() :
	http_get_request_headers();
return new HTTP_Header($headers);
```

However, there might be other places like [here](https://github.com/kohana/core/blob/3.3/master/classes/Kohana/HTTP.php#L98), where we are using the extension. Also, I am not sure how we can test.

**Comment by shadowhand** [comment]
@enov you can sign up for PagodaBox for a trial. They won't charge you for the first 48 hours.

**Comment by enov** [comment]
I have signed up for PagodaBox, and deployed a standard Kohana app:

```php
echo phpversion('http'); // outputs 2.4.3
```
```php
echo version_compare(phpversion('http'), '2.0.0', '>='); // outputs 1
```
```php
$headers = version_compare(phpversion('http'), '2.0.0', '>=') ?
			 \http\Env::getRequestHeader() :
			http_get_request_headers();
var_dump($headers);
/*
outputs:
array(12) {
  ["Authorization"]=&gt;
  string(0) ""
  ["Host"]=&gt;
  string(18) "kohana.gopagoda.io"
  ["Cache-Control"]=&gt;
  string(9) "max-age=0"
  ["Accept"]=&gt;
  string(74) "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/*;q=0.8"
  ["User-Agent"]=&gt;
  string(131) "Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36"
  ["Accept-Encoding"]=&gt;
  string(19) "gzip, deflate, sdch"
  ["Accept-Language"]=&gt;
  string(32) "en-US,en;q=0.8,fr;q=0.6,hy;q=0.4"
  ["If-Modified-Since"]=&gt;
  string(29) "Thu, 14 May 2015 06:56:20 GMT"
  ["Connection"]=&gt;
  string(10) "Keep-Alive"
  ["X-Forwarded-Port"]=&gt;
  string(2) "80"
  ["X-Forwarded-Proto"]=&gt;
  string(4) "http"
  ...
}
*/
```

**Comment by AnasSafi** [comment]
The CSS files dose not loaded until now...!!

**Comment by enov** [comment]
This is just to follow up that this was fixed for version 3.3 [here](https://github.com/kohana/core/pull/608). We need to do a release soon, and then deploy the release to the website. It will probably fix the 3.3 docs, but not the docs of older versions.

**Comment by enov** [comment]
In order to fix for all versions, we probably need to get rid of the [http extension in the Boxfile](https://github.com/kohana/kohanaframework.org/blob/master/Boxfile#L18).

**Comment by shadowhand** [comment]
@enov removing the http extension appears to have fixed the issue for all versions. Thanks!
